/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Exemplar;
import model.Livro;
import model.MaterialDigital;
import model.Revista;
import model.TipoMaterial;

/**
 *
 * @author Beatriz
 */
public class AdicionarExemplar extends javax.swing.JDialog {

    /**
     * Creates new form incluirObra
     * @param parent
     * @param modal
     */
    public AdicionarExemplar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setResizable(false);
        buttonGroup1.add(radLivro);
        buttonGroup1.add(radRevista);
        buttonGroup1.add(radMaterial);
        txbAutorLivro.setEnabled(false);
        txbAnoLivro.setEnabled(false);
        txbEdicaoLivro.setEnabled(false);
        txbEdicaoRevista.setEnabled(false);
        txbDataRevista.setEnabled(false);
        txbAnoMaterial.setEnabled(false);
        ddlTipoMaterial.setEnabled(false);
        ddlTipoMaterial.addItem("Selecione");
        
        for (TipoMaterial tipo : TipoMaterial.values()) {
            ddlTipoMaterial.addItem(tipo.getDescricao());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDescricaoTela = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txbNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        radRevista = new javax.swing.JRadioButton();
        radLivro = new javax.swing.JRadioButton();
        txbAutorLivro = new javax.swing.JTextField();
        lblAutorLivro = new javax.swing.JLabel();
        lblEdicaoRevista = new javax.swing.JLabel();
        lblEdicaoLivro = new javax.swing.JLabel();
        lblAnoLivro = new javax.swing.JLabel();
        lblDataRevista = new javax.swing.JLabel();
        lblTipoMaterial = new javax.swing.JLabel();
        lblAnoMaterial = new javax.swing.JLabel();
        radMaterial = new javax.swing.JRadioButton();
        ddlTipoMaterial = new javax.swing.JComboBox();
        txbEdicaoLivro = new javax.swing.JFormattedTextField();
        txbAnoLivro = new javax.swing.JFormattedTextField();
        txbEdicaoRevista = new javax.swing.JFormattedTextField();
        txbDataRevista = new javax.swing.JFormattedTextField();
        txbAnoMaterial = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDescricaoTela.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblDescricaoTela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescricaoTela.setText("Cadastrar exemplar");

        lblNome.setText("Nome: ");

        radRevista.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        radRevista.setText("Revista");
        radRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radRevistaActionPerformed(evt);
            }
        });

        radLivro.setText("Livro");
        radLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLivroActionPerformed(evt);
            }
        });

        txbAutorLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txbAutorLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbAutorLivroActionPerformed(evt);
            }
        });

        lblAutorLivro.setText("Autor:");

        lblEdicaoRevista.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEdicaoRevista.setText("Edição:");

        lblEdicaoLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblEdicaoLivro.setText("Edição:");

        lblAnoLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAnoLivro.setText("Ano de publicação:");

        lblDataRevista.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblDataRevista.setText("Data de publicação:");

        lblTipoMaterial.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblTipoMaterial.setText("Tipo de material:");

        lblAnoMaterial.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        lblAnoMaterial.setText("Ano de publicação:");

        radMaterial.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        radMaterial.setText("Material Digital");
        radMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMaterialActionPerformed(evt);
            }
        });

        ddlTipoMaterial.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        ddlTipoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddlTipoMaterialActionPerformed(evt);
            }
        });

        txbEdicaoLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txbEdicaoLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txbEdicaoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbEdicaoLivroActionPerformed(evt);
            }
        });

        txbAnoLivro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        txbAnoLivro.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        txbAnoLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbAnoLivroActionPerformed(evt);
            }
        });

        txbEdicaoRevista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txbEdicaoRevista.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txbDataRevista.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txbDataRevista.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        txbAnoMaterial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));
        txbAnoMaterial.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txbNome))
                    .addComponent(radRevista, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radMaterial, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(radLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAutorLivro)
                                            .addComponent(lblEdicaoLivro)
                                            .addComponent(lblAnoLivro))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txbAutorLivro)
                                            .addComponent(txbEdicaoLivro)
                                            .addComponent(txbAnoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAnoMaterial)
                                            .addComponent(lblTipoMaterial))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txbAnoMaterial)
                                            .addComponent(ddlTipoMaterial, 0, 162, Short.MAX_VALUE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataRevista)
                                    .addComponent(lblEdicaoRevista))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txbDataRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txbEdicaoRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(167, 167, 167))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(radLivro))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutorLivro)
                            .addComponent(txbAutorLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdicaoLivro)
                            .addComponent(txbEdicaoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnoLivro)
                            .addComponent(txbAnoLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(radRevista)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdicaoRevista)
                    .addComponent(txbEdicaoRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataRevista)
                    .addComponent(txbDataRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(radMaterial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnoMaterial)
                    .addComponent(txbAnoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoMaterial)
                    .addComponent(ddlTipoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCadastrar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescricaoTela)
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDescricaoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Exemplar obra;
        
        String nome = txbNome.getText();
        String autorLivro = txbAutorLivro.getText();
        String edicaoLivro = txbEdicaoLivro.getText();
        String anoLivro = txbAnoLivro.getText();
        String dataRevista = txbDataRevista.getText();
        String edicaoRevista = txbEdicaoRevista.getText();
        String anoMaterial = txbAnoMaterial.getText();
        
        String dataString = txbDataRevista.getText();
        
        boolean cadastrou = false;
        
        if(!nome.isEmpty() && nome != null && nome != "")
        {
            if(radLivro.isSelected())
            {
                if((!autorLivro.isEmpty() && autorLivro != null && autorLivro != "") 
                    && (!edicaoLivro.isEmpty() && edicaoLivro != null && edicaoLivro != "")
                    && (!anoLivro.isEmpty() && anoLivro != null && anoLivro != "")){
                    obra = new Livro(autorLivro,Integer.parseInt(anoLivro),Integer.parseInt(edicaoLivro));     
                    obra.setNome(nome);
                    try {
                        Main.getInstance().getBiblioteca().incluirObra(obra);
                        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
                        cadastrou = true;
                    } catch (Exception ex) {
                        Logger.getLogger(AdicionarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                }
            }

            else if(radRevista.isSelected())
            {
                if((!dataRevista.isEmpty() && dataRevista != null  && dataRevista != "")
                    &&(!edicaoRevista.isEmpty() && edicaoRevista != null && edicaoRevista != "")){
                    String[] dataSplit = dataString.split("/");

                    int dia = Integer.valueOf(dataSplit[0]);
                    int mes = Integer.valueOf(dataSplit[1]);
                    int ano = Integer.valueOf(dataSplit[2]);

                    LocalDate dataRevistaFormatada = LocalDate.of(ano, mes, dia); 

                    obra = new Revista(dataRevistaFormatada,Integer.parseInt(edicaoRevista));
                    obra.setNome(nome);

                    try {
                        Main.getInstance().getBiblioteca().incluirObra(obra);
                        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
                        cadastrou = true;
                    } catch (Exception ex) {
                        Logger.getLogger(AdicionarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                    }
                }
                else {
                    JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                }
            }

            else if(radMaterial.isSelected()){
                if((!anoMaterial.isEmpty() && anoMaterial != null && anoMaterial != "")){
                    obra = new MaterialDigital(Integer.parseInt(anoMaterial),TipoMaterial.getTipoPorDescricao((String) ddlTipoMaterial.getSelectedItem()));
                    obra.setNome(nome);
                    try {
                        Main.getInstance().getBiblioteca().incluirObra(obra);
                        JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
                        cadastrou = true;
                    } catch (Exception ex) {
                        Logger.getLogger(AdicionarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
        }
        
        if (cadastrou){
            txbAutorLivro.setEnabled(false);
            txbAnoLivro.setEnabled(false);
            txbEdicaoLivro.setEnabled(false);
            txbEdicaoRevista.setEnabled(false);
            txbDataRevista.setEnabled(false);
            txbAnoMaterial.setEnabled(false);
            ddlTipoMaterial.setEnabled(false);
            txbNome.setText("");
            txbAutorLivro.setText("");
            txbAnoLivro.setText("");
            txbEdicaoLivro.setText("");
            txbEdicaoRevista.setText("");
            txbDataRevista.setText("");
            txbAnoMaterial.setText("");
            ddlTipoMaterial.setEnabled(false);
            ddlTipoMaterial.setSelectedIndex(0);
            radLivro.setSelected(false);
            radMaterial.setSelected(false);
            radRevista.setSelected(false);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txbAnoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbAnoLivroActionPerformed

    }//GEN-LAST:event_txbAnoLivroActionPerformed

    private void txbEdicaoLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbEdicaoLivroActionPerformed

    }//GEN-LAST:event_txbEdicaoLivroActionPerformed

    private void ddlTipoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddlTipoMaterialActionPerformed

    }//GEN-LAST:event_ddlTipoMaterialActionPerformed

    private void radMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMaterialActionPerformed
        txbAnoMaterial.setEnabled(true);
        ddlTipoMaterial.setEnabled(true);
        txbAutorLivro.setEnabled(false);
        txbAnoLivro.setEnabled(false);
        txbEdicaoLivro.setEnabled(false);
        txbDataRevista.setEnabled(false);
        txbEdicaoRevista.setEnabled(false);
        txbAutorLivro.setText("");
        txbAnoLivro.setText("");
        txbEdicaoLivro.setText("");
        txbDataRevista.setText("");
        txbEdicaoRevista.setText("");
    }//GEN-LAST:event_radMaterialActionPerformed

    private void txbAutorLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbAutorLivroActionPerformed

    }//GEN-LAST:event_txbAutorLivroActionPerformed

    private void radLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLivroActionPerformed
        txbAutorLivro.setEnabled(true);
        txbAnoLivro.setEnabled(true);
        txbEdicaoLivro.setEnabled(true);
        txbDataRevista.setEnabled(false);
        txbEdicaoRevista.setEnabled(false);
        txbAnoMaterial.setEnabled(false);
        ddlTipoMaterial.setEnabled(false);
        txbDataRevista.setText("");
        txbEdicaoRevista.setText("");
        txbAnoMaterial.setText("");
        ddlTipoMaterial.setSelectedIndex(0);
    }//GEN-LAST:event_radLivroActionPerformed

    private void radRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radRevistaActionPerformed
        txbDataRevista.setEnabled(true);
        txbEdicaoRevista.setEnabled(true);
        txbAutorLivro.setEnabled(false);
        txbAnoLivro.setEnabled(false);
        txbEdicaoLivro.setEnabled(false);
        txbAnoMaterial.setEnabled(false);
        ddlTipoMaterial.setEnabled(false);
        txbAutorLivro.setText("");
        txbAnoLivro.setText("");
        txbEdicaoLivro.setText("");
        txbAnoMaterial.setText("");
        ddlTipoMaterial.setSelectedIndex(0);
    }//GEN-LAST:event_radRevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarExemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdicionarExemplar dialog = new AdicionarExemplar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox ddlTipoMaterial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnoLivro;
    private javax.swing.JLabel lblAnoMaterial;
    private javax.swing.JLabel lblAutorLivro;
    private javax.swing.JLabel lblDataRevista;
    private javax.swing.JLabel lblDescricaoTela;
    private javax.swing.JLabel lblEdicaoLivro;
    private javax.swing.JLabel lblEdicaoRevista;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipoMaterial;
    private javax.swing.JRadioButton radLivro;
    private javax.swing.JRadioButton radMaterial;
    private javax.swing.JRadioButton radRevista;
    private javax.swing.JFormattedTextField txbAnoLivro;
    private javax.swing.JFormattedTextField txbAnoMaterial;
    private javax.swing.JTextField txbAutorLivro;
    private javax.swing.JFormattedTextField txbDataRevista;
    private javax.swing.JFormattedTextField txbEdicaoLivro;
    private javax.swing.JFormattedTextField txbEdicaoRevista;
    private javax.swing.JTextField txbNome;
    // End of variables declaration//GEN-END:variables
}
