package view;

import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Aluno;
import model.Professor;

/**
 *
 * @author Beatriz
 */
public class AdicionarUsuario extends javax.swing.JDialog
{
    /**
     * Creates new form incluirUsuario
     * @param parent
     * @param modal
     */
    public AdicionarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txbAdmissao.setEnabled(false);
        txbCodigoMatricula.setEnabled(false);
        buttonGroup1.add(radProfessor);
        buttonGroup1.add(radAluno);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblDescricaoTela = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txbNome = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        radAluno = new javax.swing.JRadioButton();
        radProfessor = new javax.swing.JRadioButton();
        lblDataAdmissao = new javax.swing.JLabel();
        txbAdmissao = new javax.swing.JFormattedTextField();
        btnCadastrar = new javax.swing.JButton();
        lblCodigoMatricula = new javax.swing.JLabel();
        txbCodigoMatricula = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblDescricaoTela.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lblDescricaoTela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDescricaoTela.setText("Cadastrar usuário");

        txbNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbNomeActionPerformed(evt);
            }
        });

        lblNome.setText("Nome: ");

        radAluno.setText("Aluno");
        radAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAlunoActionPerformed(evt);
            }
        });

        radProfessor.setText("Professor");
        radProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radProfessorActionPerformed(evt);
            }
        });

        lblDataAdmissao.setText("Data Admissão:");

        txbAdmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.MEDIUM))));
        txbAdmissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbAdmissaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txbNome))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDataAdmissao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txbAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(radProfessor))
                    .addComponent(radAluno))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txbNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataAdmissao)
                    .addComponent(txbAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radAluno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblCodigoMatricula.setText("Código Matricula:");

        txbCodigoMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txbCodigoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txbCodigoMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCodigoMatricula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txbCodigoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescricaoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblDescricaoTela, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoMatricula)
                    .addComponent(txbCodigoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String nome = txbNome.getText(); 
        String dataString = txbAdmissao.getText();
        String matricula = txbCodigoMatricula.getText();
       
        if (!nome.isEmpty() && nome != null && nome != ""){
            if(radProfessor.isSelected() && (!dataString.isEmpty() && dataString != null && dataString != ""))
            {
                String[] dataStrSplit = dataString.split("/");

                int dia = Integer.valueOf(dataStrSplit[0]);
                int mes = Integer.valueOf(dataStrSplit[1]);
                int ano = Integer.valueOf(dataStrSplit[2]);

                LocalDate dataCorretaAdmissao = LocalDate.of(ano, mes, dia);

                Professor professor = new Professor(dataCorretaAdmissao);
                professor.setNome(nome);

                try {
                    Main.getInstance().getBiblioteca().incluirUsuario(professor);
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
                } catch (Exception ex) {
                    Logger.getLogger(AdicionarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                }
            }
            else if(radAluno.isSelected() && (!matricula.isEmpty() && matricula != null && matricula != ""))
            {
                Aluno aluno = new Aluno();
                aluno.setNome(nome);
                aluno.setMatricula(Integer.parseInt(matricula));
                try {
                    Main.getInstance().getBiblioteca().incluirUsuario(aluno);
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
                } catch (Exception ex) {
                    Logger.getLogger(AdicionarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser preenchidos");
        }
                
        txbNome.setText("");
        txbAdmissao.setText("");
        txbCodigoMatricula.setText("");
        
        txbCodigoMatricula.setEnabled(false);
        txbAdmissao.setEnabled(false);
            
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txbCodigoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbCodigoMatriculaActionPerformed
        
    }//GEN-LAST:event_txbCodigoMatriculaActionPerformed

    private void radProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radProfessorActionPerformed
        txbAdmissao.setEnabled(true);
        
        txbCodigoMatricula.setEnabled(false);
    }//GEN-LAST:event_radProfessorActionPerformed

    private void radAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAlunoActionPerformed
        txbCodigoMatricula.setEnabled(true);
        
        txbAdmissao.setEnabled(false);
    }//GEN-LAST:event_radAlunoActionPerformed

    private void txbAdmissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbAdmissaoActionPerformed
        
    }//GEN-LAST:event_txbAdmissaoActionPerformed

    private void txbNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txbNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txbNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdicionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdicionarUsuario dialog = new AdicionarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigoMatricula;
    private javax.swing.JLabel lblDataAdmissao;
    private javax.swing.JLabel lblDescricaoTela;
    private javax.swing.JLabel lblNome;
    private javax.swing.JRadioButton radAluno;
    private javax.swing.JRadioButton radProfessor;
    private javax.swing.JFormattedTextField txbAdmissao;
    private javax.swing.JFormattedTextField txbCodigoMatricula;
    private javax.swing.JTextField txbNome;
    // End of variables declaration//GEN-END:variables
}
